// src/app/[slug]/page.tsx
import { notFound } from "next/navigation";
import { Metadata } from "next";
import { Maps } from "@/data/maps";
import MapContainer from "@/components/map/MapContainer";

function slugFor(link: string) {
  return link.replace(/^\//, "");
}

function findMap(slug: string) {
  return Maps.find((map) => slugFor(map.link) === slug);
}

export function generateStaticParams() {
  return Maps.map((map) => ({ slug: slugFor(map.link) }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const map = findMap(slug);
  return { title: map ? `Map - ${map.name}` : "Tarkov Maps" };
}

export default async function MapPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const map = findMap(slug);

  if (!map) {
    notFound();
  }

  return (
    <>
      <h1 className="page-heading">{map.name}</h1>
      <MapContainer key={slug} mapUrl={map.img} mapCredit={map.credit} />
    </>
  );
}

// pages/[slug].vue
<template>
  <h1 class="page-heading" v-if="map">{{ map.name }}</h1>
  <MapContainer v-if="map" :key="map.name" :map-url="map.img" :mapCredit="map.credit" />
</template>

<script lang="ts" setup>
import { Maps } from '~/maps';

const route = useRoute();

const mapName = route.params.slug;

const map = Maps.find(m => m.link === mapName);

// If the map is not found, return a 404
if (!map) {
  throw createError({ statusCode: 404, message: 'Map not found' });
}

useHead({
  title: `Map - ${map.name}`
});

</script>

<style>

</style>
