// src/components/MapContainer.vue
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import {MapCredit} from "../models/MapDefinition.ts";


const props = defineProps<{
  mapUrl: string;
  mapCredit?: MapCredit;
}>();

const storedZoom = localStorage.getItem(`${encodeURIComponent(props.mapUrl)}_zoom`);
const storedCenter = localStorage.getItem(`${encodeURIComponent(props.mapUrl)}_center`);

const zoom = ref(2.5);
const size = ref([0, 0]);
const center = ref([0, 0]);
const extent = computed(() => [0, 0, ...size.value]);
const projection = reactive({
  code: "xkcd-image",
  units: "pixels",
  extent: extent
});
const image = ref<string | null>(null);
const imgCopyright = ref(props.mapCredit ? `Map By <a target='_blank' href="${props.mapCredit.creditLink}">${props.mapCredit.creditText}</a>` : null);

onMounted(() => {
  const img = new Image();
  img.src = props.mapUrl;
  img.onload = () => {
    image.value = props.mapUrl;

    zoom.value = storedZoom ? parseFloat(storedZoom) : 2.5;
    size.value = [img.width, img.height];
    center.value = storedCenter ? JSON.parse(storedCenter) : [img.width / 2, img.height / 2];
  };
});

const onZoomChange = (e: any) => {
  const zoom = e.target.getZoom();

  if (isNaN(zoom))
    return;

  localStorage.setItem(`${encodeURIComponent(props.mapUrl)}_zoom`, zoom);
};

const onCenterChange = (e: any) => {
  const center = e.target.getCenter();

  if (isNaN(center[0]) || isNaN(center[1]))
    return;

  localStorage.setItem(`${encodeURIComponent(props.mapUrl)}_center`, JSON.stringify(center));
};

</script>

<template>
  <ol-map v-if="image"
    :loadTilesWhileAnimating="true"
    :loadTilesWhileInteracting="true"
    class="w-full flex-1"
    @change='(e: any) => console.log("Changed", e)'
  >
    <ol-view
      ref="view"
      :center="center"
      :zoom="zoom"
      :projection="projection"
      @change:center="onCenterChange"
      @change:resolution="onZoomChange"
    />
    <ol-fullscreen-control />
    <ol-attribution-control />

    <ol-rotate-control />
    <ol-zoom-control />
    <ol-zoomslider-control />
    
    <ol-image-layer id="xkcd">
      <ol-source-image-static
        :url="image"
        :imageSize="size"
        :imageExtent="extent"
        :projection="projection"
        :attributions="imgCopyright"
      ></ol-source-image-static>
    </ol-image-layer>
  </ol-map>
</template>

<style scoped>

</style>

// src/components/map/MapContainer.tsx
"use client";

import { useEffect, useRef } from "react";
import Map from "ol/Map";
import View from "ol/View";
import ImageLayer from "ol/layer/Image";
import ImageStatic from "ol/source/ImageStatic";
import Projection from "ol/proj/Projection";
import { defaults as defaultControls } from "ol/control";
import FullScreen from "ol/control/FullScreen";
import Attribution from "ol/control/Attribution";
import Rotate from "ol/control/Rotate";
import Zoom from "ol/control/Zoom";
import ZoomSlider from "ol/control/ZoomSlider";
import "ol/ol.css";
import { MapCredit } from "@/models/MapDefinition";

interface MapContainerProps {
  mapUrl: string;
  mapCredit?: MapCredit;
}

export default function MapContainer({ mapUrl, mapCredit }: MapContainerProps) {
  const containerRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    let cancelled = false;
    let olMap: Map | null = null;

    const storedZoom = localStorage.getItem(`${encodeURIComponent(mapUrl)}_zoom`);
    const storedCenter = localStorage.getItem(`${encodeURIComponent(mapUrl)}_center`);

    const img = new Image();
    img.src = mapUrl;
    img.onload = () => {
      if (cancelled || !containerRef.current) return;

      const size: [number, number] = [img.width, img.height];
      const extent: [number, number, number, number] = [0, 0, size[0], size[1]];

      const projection = new Projection({
        code: "xkcd-image",
        units: "pixels",
        extent,
      });

      const zoom = storedZoom ? parseFloat(storedZoom) : 2.5;
      const center: [number, number] = storedCenter
        ? JSON.parse(storedCenter)
        : [size[0] / 2, size[1] / 2];

      const imgCopyright = mapCredit
        ? `Map By <a target='_blank' href="${mapCredit.creditLink}">${mapCredit.creditText}</a>`
        : undefined;

      const view = new View({
        center,
        zoom,
        projection,
      });

      olMap = new Map({
        target: containerRef.current,
        view,
        controls: defaultControls({ attribution: false, zoom: false, rotate: false }).extend([
          new FullScreen(),
          new Attribution({ collapsible: true }),
          new Rotate(),
          new Zoom(),
          new ZoomSlider(),
        ]),
        layers: [
          new ImageLayer({
            source: new ImageStatic({
              url: mapUrl,
              imageExtent: extent,
              projection,
              attributions: imgCopyright,
            }),
          }),
        ],
      });

      olMap.updateSize();

      view.on("change:center", () => {
        const newCenter = view.getCenter();
        if (!newCenter || isNaN(newCenter[0]) || isNaN(newCenter[1])) return;
        localStorage.setItem(`${encodeURIComponent(mapUrl)}_center`, JSON.stringify(newCenter));
      });

      view.on("change:resolution", () => {
        const newZoom = view.getZoom();
        if (newZoom === undefined || isNaN(newZoom)) return;
        localStorage.setItem(`${encodeURIComponent(mapUrl)}_zoom`, String(newZoom));
      });
    };

    return () => {
      cancelled = true;
      olMap?.setTarget(undefined);
      olMap = null;
    };
  }, [mapUrl, mapCredit]);

  return <div ref={containerRef} className="w-full flex-1" />;
}
